# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7775626f491447317d9f6394cfe5bf387ab06064ca72f9be4faed8ec51465c6313acef0db84187fd870a455638a973646c8ca2636ef98fe2f38a909cc2273d37

test:
  secret_key_base: 607761c670a86db4136b23e3a20c430ee7bcf9b4fc2009f9c80e9c1200be458f3877108ae7ce67551e6a254038d82d38cf119ea11ed340ad9bc5cd56ec1bf27f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
